Repository bbta3-bppt/aerobro, pull requests merged in 2021-05, with the labels that each got.

#35 Optimalisasi fungsi thread untuk mqtt
  src/helpers.rs
  src/models.rs
Labels: maintenance

#36 Memperbarui node package untuk keamanan
  ui/package-lock.json
  ui/package.json
Labels: dependencies

#38 Menerapkan dotenv kedalam fungsi helper
  README.md
  proc/helper.py
  proc/index.py
  proc/requirements.txt
Labels: dependencies, documentation, maintenance

#39 Koreksi README dan perbarui gitignore
  .gitignore
  README.md
Labels: documentation

#40 Ganti penerapan environment variable untuk ui
  ui/package-lock.json
  ui/package.json
  ui/quasar.conf.js
Labels: dependencies, maintenance

#41 Menambahkan fitur proses data sensor kedalam db
  .gitignore
  README.md
  proc/handler.py
  proc/helper.py
  proc/requirements.txt
Labels: enhancement

#42 Penyesuaian workflow untuk deploy
  .github/workflows/deploy.yml
Labels: maintenance

#43 Ganti mekanisme deploy dan update readme
  .github/workflows/deploy.yml
  README.md
Labels: documentation, maintenance

#44 Terapan lanjut ssr kedalam web melalui EventSource
  src/helpers.rs
  src/models.rs
  ui/src/pages/utama/utama.js
Labels: maintenance
