Repository bbta3-bppt/aerobro, pull requests merged in 2021-01, with the labels that each got.

#1 kelola awal struktur aplikasi dan workflow
  .gitignore
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: maintenance

#2 modifikasi layout dan font
  .gitignore
  src_ui/.editorconfig
  src_ui/.eslintignore
  src_ui/.eslintrc.js
  src_ui/.postcssrc.js
  src_ui/README.md
  src_ui/babel.config.js
  src_ui/jsconfig.json
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/public/favicon.ico
  src_ui/public/icons/favicon-128x128.png
  src_ui/public/icons/favicon-16x16.png
  src_ui/public/icons/favicon-32x32.png
  src_ui/public/icons/favicon-96x96.png
  src_ui/quasar.conf.js
  src_ui/src/App.vue
  src_ui/src/assets/quasar-logo-full.svg
  src_ui/src/boot/.gitkeep
  src_ui/src/boot/axios.js
  src_ui/src/components/EssentialLink.vue
  src_ui/src/css/app.sass
  src_ui/src/css/default/_base.sass
  src_ui/src/css/quasar.variables.sass
  src_ui/src/index.template.html
  src_ui/src/layouts/MainLayout.vue
  src_ui/src/pages/Error404.vue
  src_ui/src/pages/Index.vue
  src_ui/src/router/index.js
  src_ui/src/router/routes.js
  src_ui/src/store/index.js
  src_ui/src/store/module-example/actions.js
  src_ui/src/store/module-example/getters.js
  src_ui/src/store/module-example/index.js
  src_ui/src/store/module-example/mutations.js
  src_ui/src/store/module-example/state.js
  src_ui/src/store/store-flag.d.ts
Labels: maintenance

#3 kelola tampilan halaman utama
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/src/components/EssentialLink.vue
  src_ui/src/components/jembatan/Jembatan.vue
  src_ui/src/components/jembatan/jembatanHandler.js
  src_ui/src/pages/Index.vue
  src_ui/src/pages/utama/Index.vue
  src_ui/src/pages/utama/utama.js
  src_ui/src/router/routes.js
Labels: enhancement

#4 memuat jembatan 3d ke halaman aplikasi
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/public/models/jembatan.mtl
  src_ui/public/models/jembatan.obj
  src_ui/src/assets/quasar-logo-full.svg
  src_ui/src/components/jembatan/jembatanHandler.js
Labels: enhancement

#5 modifikasi pengaturan camera dan GUI awal
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/public/models/jembatan.obj
  src_ui/src/components/jembatan/Jembatan.vue
  src_ui/src/components/jembatan/jembatanHandler.js
  src_ui/src/pages/utama/Index.vue
  src_ui/src/pages/utama/utama.js
Labels: maintenance

#6 bump up ui version
  src_ui/package-lock.json
Labels: maintenance

#7 Live data sensor melalui socket
  src_socket/handlers/disconnectHandler.js
  src_socket/handlers/emitHandler.js
  src_socket/index.js
  src_socket/package-lock.json
  src_socket/package.json
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/quasar.conf.js
  src_ui/src/boot/socket.js
  src_ui/src/components/jembatan/jembatanHandler.js
  src_ui/src/css/default/_base.sass
  src_ui/src/pages/utama/Index.vue
  src_ui/src/pages/utama/utama.js
  src_ui/src/store/index.js
  src_ui/src/store/jembatan/actions.js
  src_ui/src/store/jembatan/getters.js
  src_ui/src/store/jembatan/index.js
  src_ui/src/store/jembatan/mutations.js
  src_ui/src/store/jembatan/state.js
  src_ui/src/store/module-example/actions.js
  src_ui/src/store/module-example/getters.js
  src_ui/src/store/module-example/mutations.js
  src_ui/src/store/module-example/state.js
Labels: enhancement

#8 bump up ui version
  src_ui/package-lock.json
Labels: maintenance

#9 Bacaan status data sensor secara dinamis
  README.md
  src_socket/handlers/emitHandler.js
  src_socket/index.js
  src_ui/quasar.conf.js
  src_ui/src/pages/utama/Index.vue
  src_ui/src/pages/utama/utama.js
  src_ui/src/store/jembatan/state.js
Labels: maintenance

#10 penyesuaian socket client untuk state sinyal dan dokumentasi
  README.md
  src_socket/handlers/disconnectHandler.js
  src_socket/handlers/errorHandler.js
  src_socket/index.js
  src_ui/package-lock.json
  src_ui/package.json
  src_ui/src/pages/utama/Index.vue
  src_ui/src/pages/utama/utama.js
  src_ui/src/store/jembatan/mutations.js
  src_ui/src/store/jembatan/state.js
Labels: documentation, maintenance
